spring.application.name=artifex-capital-backend
server.servlet.context-path=/api/v1

# Base de Datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Seguridad JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

# Configuración de Resend (Referencia opcional, el código la lee de la variable de entorno)
resend.api.key=${RESEND_API_KEY}